version: '2'
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
    driver: local
