default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password:

development:
  <<: *default
  database: ht_development

test:
  <<: *default
  database: ht_test
